package:
  name: plot
  version: 0.1.3

build:
  number: 0
  noarch: true

source:
  git_url: https://github.com/jonathonmcmurray/plot.git

requirements:
  run:
    - qutil
    - matplotlib

about:
  home: https://github.com/jonathonmcmurray/plot
  license: MIT
  summary: Simple plots for kdb+/q
